env:
  GITHUB_COMMIT_STATUS_ENABLED: 'true'
  GITHUB_COMMIT_STATUS_CONTEXT: 'buildkite/kibana-ci-baseline'
steps:
  - command: .buildkite/scripts/lifecycle/pre_build.sh
    label: Pre-Build

  - wait

  - command: .buildkite/scripts/steps/baseline.sh
    label: Default Build and Metrics
    agents:
      queue: baseline

  - command: .buildkite/scripts/steps/baseline_ts_refs_api_docs.sh
    label: Build TS Refs and Check Public API Docs
    agents:
      queue: baseline-small

  - wait: ~
    continue_on_failure: true

  - command: .buildkite/scripts/lifecycle/post_build.sh
    label: Post-Build
